server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, busrefresh

spring:
  application:
    name: bbl-career

  profiles:
    active: dev

  cloud:
    config:
      name: bbl-career
      aws:
        s3:
          bucket: bbl-career
        credentials:
          access-key:
          secret-key:
        region:
          static: ap-northeast-2
          auto: false
        stack:
          auto: true
    logging:
      level:
        com:
          amazonaws:
            util:
              EC2MetadataUtils: ERROR

  config:
    import: configserver:http://ec2-13-124-49-255.ap-northeast-2.compute.amazonaws.com:8888/

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  redis:
    host: localhost
    port: 6379

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  main:
    allow-bean-definition-overriding: true
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://bbleureka-env.eba-sk7czfia.ap-northeast-2.elasticbeanstalk.com/eureka
