# MySQL Driver
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver

# DB URL
spring.datasource.url: jdbc:mysql://localhost:3306/bbl_career?verifyServerCertificate=false&useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true

# DB username
spring.datasource.username: root

# DB password
spring.datasource.password: 1022

# 콘솔에 SQL 출력 여부
spring.jpa.show-sql: true

# DDL 기능 사용 여부(create/update/create-drop/validate/none)
spring.jpa.hibernate.ddl-auto: update


server:
  port: 0 #gateway random Port - Hong HyuckJune

jwt:
  secret: ADBF#!@$DAOGEB@N!%^#$%$#*@K@!GDS<M
spring:
  application:
    name: bbl-career #gateway service name - Hong HyuckJune
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  profiles:
    active:
      default

  jackson:
    serialization:
      fail-on-empty-beans: false


eureka: #eureka Load Balancer Add - Hong HyuckJune
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: bbleureka-env.eba-sk7czfia.ap-northeast-2.elasticbeanstalk.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}/eureka/

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

cloud:
  aws:
    s3:
      bucket: bbl-career
    credentials:
      access-key:
      secret-key:
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR