server:
  port: 8000

jwt:
  secret: ADBF#!@$DAOGEB@N!%^#$%$#*@K@!GDS<M

eureka:
  instance:
    prefer-ip-address: true
    hostname: bbleureka-env.eba-sk7czfia.ap-northeast-2.elasticbeanstalk.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: bbl-gateway
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
           baseMessage: Spring Cloud Gateway GlobalFilter
           preLogger: true
           postLogger: true
      routes:
        - id: bbl-career
          uri: lb://BBL-CAREER
          predicates:
            - Path=/bbl-career/careers/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/bbl-career/(?<segment>.*), /$\{segment}
            - CustomFilter

        - id: bbl-member
          uri: lb://BBL-MEMBER
          predicates:
            - Path=/bbl-member/members/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/bbl-member/(?<segment>.*), /$\{segment}
            - MemberFilter

        - id: bbl-member
          uri: lb://BBL-MEMBER
          predicates:
            - Path=/bbl-member/members/signUp
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/bbl-member/(?<segment>.*), /$\{segment}
            - MemberFilter

        - id: bbl-member
          uri: lb://BBL-MEMBER
          predicates:
            - Path=/bbl-member/members/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/bbl-member/(?<segment>.*), /$\{segment}
            - name: MemberFilter
            - name: JwtAuthorizationHeaderFilter

        - id: bbl-payment
          uri: lb://BBL-PAYMENT
          predicates:
            - Path=/bbl-payment/payments/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/bbl-payment/(?<segment>.*), /$\{segment}
            - CustomFilter