server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, busrefresh

spring:
  application:
    name: bbl-member

  profiles:
    active: dev

  cloud:
    config:
      name: application

  config:
    import: optional:configserver:http://127.0.0.1:8888

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  redis:
    host: localhost
    port: 6379  #redis base port number

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


eureka: #eureka Load Balancer Add - Hong HyuckJune
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: bbleureka-env.eba-sk7czfia.ap-northeast-2.elasticbeanstalk.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
