jwt:
  secret: ADBF#!@$DAOGEB@N!%^#$%$#*@K@!GDS<M

server:
  port: 0

spring:
  application:
    name: bbl-member

  redis:
    host: localhost
    port: 6379  #redis base port number

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


eureka: #eureka Load Balancer Add - Hong HyuckJune
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: bbleureka-env.eba-sk7czfia.ap-northeast-2.elasticbeanstalk.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}/eureka/
