server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, busrefresh

spring:
  application:
    name: bbl-payment

  profiles:
    active: dev

  cloud:
    config:
      name: application

  config:
    import: configserver:http://ec2-13-124-49-255.ap-northeast-2.compute.amazonaws.com:8888/

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://bbleureka-env.eba-sk7czfia.ap-northeast-2.elasticbeanstalk.com/eureka