server:
  port: 0 #gateway random Port - Hong HyuckJune

eureka: #eureka add - Hong HyuckJune
  instance:
#    hostname: bbleureka-env.eba-sk7czfia.ap-northeast-2.elasticbeanstalk.com
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:

  main:
    allow-bean-definition-overriding: true

  application:
    name: bbl-payment #gateway service name - Hong HyuckJune
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
#      url: jdbc:h2:mem:test
#      username: sa
#      password:
#      driver-class-name: org.h2.Driver
    url: jdbc:mysql://localhost:3306/paymentdb?serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#logging:
#  level:
#    org.hibernate.SQL: debug
#    root: debug

  batch:
    jdbc:
      initialize-schema: always
    job:
      names: ${job.name:NONE}

#feign client 로그보기
feign:
  client:
    config:
      default:
        logger-level: full

jwt:
  secret: ADBF#!@$DAOGEB@N!%^#$%$#*@K@!GDS<M

